Count,Message,Traceback,Nodes
165,"[Errno Expecting value] <!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the error log for details.</p>
<p><em>Faithfully yours, nginx.</em></p>
</body>
</html>
: 0","  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 309, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 334, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 447, in execute_task
    task(self.user)
  File ""/home/testuser/locustfile.py"", line 78, in load
    city = choice(self.client.get('/api/shipping/cities/{}'.format(code['code']), headers={'x-forwarded-for': fake_ip}).json())
  File ""/usr/local/lib/python3.6/dist-packages/requests/models.py"", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
",local
77,"[Errno Expecting value] <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor=""white"">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
: 0","  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 309, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 334, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 447, in execute_task
    task(self.user)
  File ""/home/testuser/locustfile.py"", line 80, in load
    shipping = self.client.get('/api/shipping/calc/{}'.format(city['uuid']), headers={'x-forwarded-for': fake_ip}).json()
  File ""/usr/local/lib/python3.6/dist-packages/requests/models.py"", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
",local
659,"[Errno Expecting value] <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor=""white"">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
: 0","  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 309, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 334, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 447, in execute_task
    task(self.user)
  File ""/home/testuser/locustfile.py"", line 77, in load
    code = choice(self.client.get('/api/shipping/codes', headers={'x-forwarded-for': fake_ip}).json())
  File ""/usr/local/lib/python3.6/dist-packages/requests/models.py"", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
",local
29,"[Errno Expecting value] <!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the error log for details.</p>
<p><em>Faithfully yours, nginx.</em></p>
</body>
</html>
: 0","  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 309, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 334, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 447, in execute_task
    task(self.user)
  File ""/home/testuser/locustfile.py"", line 84, in load
    cart = self.client.post('/api/shipping/confirm/{}'.format(uniqueid), json=shipping, headers={'x-forwarded-for': fake_ip}).json()
  File ""/usr/local/lib/python3.6/dist-packages/requests/models.py"", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
",local
427,"[Errno Expecting value] <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor=""white"">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
: 0","  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 309, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 334, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 447, in execute_task
    task(self.user)
  File ""/home/testuser/locustfile.py"", line 50, in load
    user = self.client.get('/api/user/uniqueid', headers={'x-forwarded-for': fake_ip}).json()
  File ""/usr/local/lib/python3.6/dist-packages/requests/models.py"", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
",local
271,[Errno Expecting value] : 0,"  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 309, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 334, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 447, in execute_task
    task(self.user)
  File ""/home/testuser/locustfile.py"", line 72, in load
    cart = self.client.get('/api/cart/cart/{}'.format(uniqueid), headers={'x-forwarded-for': fake_ip}).json()
  File ""/usr/local/lib/python3.6/dist-packages/requests/models.py"", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
",local
101,[Errno Expecting value] : 0,"  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 309, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 334, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 447, in execute_task
    task(self.user)
  File ""/home/testuser/locustfile.py"", line 56, in load
    products = self.client.get('/api/catalogue/products', headers={'x-forwarded-for': fake_ip}).json()
  File ""/usr/local/lib/python3.6/dist-packages/requests/models.py"", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
",local
168,"[Errno Expecting value] <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor=""white"">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
: 0","  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 309, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 334, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.6/dist-packages/locust/user/task.py"", line 447, in execute_task
    task(self.user)
  File ""/home/testuser/locustfile.py"", line 87, in load
    order = self.client.post('/api/payment/pay/{}'.format(uniqueid), json=cart, headers={'x-forwarded-for': fake_ip}).json()
  File ""/usr/local/lib/python3.6/dist-packages/requests/models.py"", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
",local
